{
 "title": "Chain Metrics Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "chain",
    "label": "chain",
    "query": {
     "query": "label_values(substrate_build_info,chain)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(substrate_build_info{chain=~\"$chain\"},node)"
    }
   },
   {
    "name": "version",
    "label": "version",
    "query": {
     "query": "label_values(substrate_build_info{chain=~\"$chain\"},version)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(substrate_build_info{chain=~\"$chain\", node=~\"$node\"},namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "substrate_block_height{chain=~\"$chain\", node=~\"$node\", status=\"best\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "substrate_block_height{chain=~\"$chain\", node=~\"$node\", status=\"finalized\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "substrate_build_info{chain=~\"$chain\", node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "substrate_sync_peers{chain=~\"$chain\", node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "substrate_ready_transactions_number{chain=~\"$chain\", node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(substrate_block_verification_time_count{chain=~\"$chain\", node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1/rate(substrate_block_height{status=\"best\", chain=~\"$chain\", node=~\"$node\"}[$__rate_interval] )",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Finality Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_block_height{node=~\"$node\", chain=~\"$chain\", status=\"best\"} -  on(node, job) substrate_block_height{node=~\"$node\", chain=\"$chain\", status=\"finalized\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Version Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "substrate_build_info{chain=~\"$chain\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Nodes per version",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (count by (version) (substrate_build_info{chain=~\"$chain\", node=~\"$node\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Peers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=~\"$chain\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Transaction Queue",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 38 },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{chain=~\"$chain\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Per Node Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    { "title": "$node", "type": "text", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 }, "repeat": "node" },
    {
     "title": "Block Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "1/rate(substrate_block_height{status=\"best\", chain=~\"$chain\", node=~\"$node\"}[$__rate_interval] )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Finality Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 78 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "substrate_block_height{node=~\"$node\", chain=~\"$chain\", status=\"best\"} -  on(node, job) substrate_block_height{node=~\"$node\", chain=\"$chain\", status=\"finalized\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 92 },
     "repeat": "node",
     "targets": [
      {
       "expr": "substrate_sync_peers{chain=~\"$chain\", node=~\"$node\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Transaction Queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 110 },
     "repeat": "node",
     "targets": [
      {
       "expr": "substrate_ready_transactions_number{chain=~\"$chain\", node=~\"$node\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  }
 ]
}