{
 "title": "Parachains - Polkadot Introspector",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "introspector_pc_para_block_time_sum{}"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "parachain_id",
    "query": {
     "query": "introspector_pc_para_block_time_sum{chain=\"$chain\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "At a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count of parachains producing blocks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg(increase(introspector_pc_relay_block_time_count{chain=\"$chain\"}[1h])) by (parachain_id)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average parachain block time (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(increase(introspector_pc_para_block_time_sec_sum{chain=\"$chain\"}[$__rate_interval]))/avg(increase(introspector_pc_para_block_time_sec_count{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "All parachains"
    }
   ]
  },
  {
   "title": "Disputes per block ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "disputes/block" } },
   "targets": [
    {
     "expr": "6*avg(rate(introspector_pc_disputed_count{chain=\"$chain\"}[$__rate_interval])) by (parachain_id)",
     "legendFormat": "Parachain {{parachain_id}}"
    }
   ]
  },
  {
   "title": "Backed and Included candidates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Candidates/block" } },
   "targets": [
    {
     "expr": "6*sum(rate(introspector_pc_backed_count{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Total backed candidates"
    },
    {
     "expr": "6*sum(rate(introspector_pc_included_count{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Total included candidates"
    }
   ]
  },
  {
   "title": "Parachain $parachain_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "parachain_id",
   "targets": [
    {}
   ]
  },
  {
   "title": "Parachain $parachain_id block time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(increase(introspector_pc_para_block_time_sec_sum{chain=\"$chain\", parachain_id=\"$parachain_id\"}[$__rate_interval])/increase(introspector_pc_para_block_time_sec_count{chain=\"$chain\", parachain_id=\"$parachain_id\"}[$__rate_interval]))",
     "legendFormat": "Average block time"
    }
   ]
  },
  {
   "title": "Parachain $parachain_id block time (relay blocks) histogram",
   "type": "heatmap",
   "description": "Parachain block time is measured in relay chain blocks.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "increase(introspector_pc_para_block_time_bucket{chain=\"$chain\", parachain_id=\"$parachain_id\"}[$__rate_interval]) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backed and Included candidates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Candidates/block" } },
   "targets": [
    {
     "expr": "6*rate(introspector_pc_backed_count{chain=\"$chain\", parachain_id=\"$parachain_id\"}[$__rate_interval])",
     "legendFormat": "Total backed candidates"
    },
    {
     "expr": "6*rate(introspector_pc_included_count{chain=\"$chain\", parachain_id=\"$parachain_id\"}[$__rate_interval])",
     "legendFormat": "Total included candidates"
    }
   ]
  }
 ]
}