{
 "title": "Parachains - Liveliness",
 "description": "Parachain consensus KPI and debug metrics",
 "tags": [
  "Polkadot",
  "Parachains",
  "rococo",
  "kusama",
  "Versi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "label": "Chain", "query": { "query": "substrate_block_height{}" } },
   { "name": "datasource", "label": "Source of data", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Subsystem CPU usage (network avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(substrate_tasks_polling_duration_sum{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (task_group)",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Relay chain finality lag (last)",
   "type": "gauge",
   "description": "Measures how far behind finality is compared to the current best block. By design, GRANDPA never finalizes past last 2 blocks, so this value is always >=2.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(substrate_block_height{chain=\"$chain\",node=~\".*validator.*\", status=\"best\"}) - avg(substrate_block_height{chain=\"$chain\",node=~\".*validator.*\", status=\"finalized\"})"
    }
   ]
  },
  {
   "title": "Approval checking finality lag (last)",
   "type": "gauge",
   "description": "Measures how far behind finality is compared to the current best block. By design, GRANDPA never finalizes past last 2 blocks, so this value is always >=2.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(polkadot_parachain_approval_checking_finality_lag{chain=\"$chain\", node=~\".*validator.*\"})"
    }
   ]
  },
  {
   "title": "Effective Disputes Finality Lag (avg)",
   "type": "gauge",
   "description": "How far behind the chain head is the last approved and non disputed block. \nThis value is always higher than approval checking lag as it further restricts finality to only undisputed \nchains.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(polkadot_parachain_disputes_finality_lag{chain=\"$chain\", node=~\".*validator.*\"}) - avg(polkadot_parachain_approval_checking_finality_lag{chain=\"$chain\", node=~\".*validator.*\"})"
    }
   ]
  },
  {
   "title": "Node versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "count(substrate_build_info{chain=\"$chain\", node=~\".*validator.*|.*bootnode.*\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Subsystem messaging KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Bounded channel sizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "avg(increase(polkadot_parachain_subsystem_bounded_sent{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]) - on(node, subsystem_name) increase(polkadot_parachain_subsystem_bounded_received{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (subsystem_name) > 0",
     "legendFormat": "{{subsystem_name}}"
    }
   ]
  },
  {
   "title": "Substrate unbounded channel drops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(substrate_unbounded_channel_len{chain=\"$chain\", action=\"dropped\", node=~\".*validator.*\"}[$__rate_interval])) by (entity)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Clogged channels by susbystem",
   "type": "timeseries",
   "description": "Shows how many times senders blocked when sending messages to subsystems ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(rate(polkadot_parachain_subsystem_bounded_blocked{chain=\"$chain\", pod=~\".*validator.*|.*bootnode.*\"}[$__rate_interval])) by (subsystem_name)",
     "legendFormat": "{{subsystem_name}}"
    }
   ]
  },
  { "title": "Runtime API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Runtime API request status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "avg(rate(polkadot_parachain_runtime_api_requests_total{node=~\".*validator.*\", chain=\"$chain\"}[$__rate_interval])) by (success)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Runtime API request duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_runtime_api_make_runtime_api_request_bucket{chain=\"$chain\", node=~\".*validator.*\"} [$__rate_interval])) by (le) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance and scale KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Finality lag ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "avg(polkadot_parachain_approval_checking_finality_lag{chain=\"$chain\"})",
     "legendFormat": "Approval checking finality lag"
    },
    {
     "expr": "avg(substrate_block_height{chain=\"$chain\", status=\"best\", node=~\".*validator.*\"}) - on(node) avg(substrate_block_height{chain=\"$chain\", status=\"finalized\", node=~\".*validator.*\"})",
     "legendFormat": "Relay chain finality lag"
    },
    {
     "expr": "avg(polkadot_parachain_disputes_finality_lag{chain=\"$chain\", node=~\".*validator.*\"}) - avg(polkadot_parachain_approval_checking_finality_lag{chain=\"$chain\", node=~\".*validator.*\"})",
     "legendFormat": "Disputes finality lag"
    },
    {
     "expr": "avg(rate(polkadot_parachain_approval_distribution_aggression_l1_messages_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "L1 Aggression trigger(s)"
    },
    {
     "expr": "avg(rate(polkadot_parachain_approval_distribution_aggression_l2_messages_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "L2 Aggression trigger(s)"
    }
   ]
  },
  {
   "title": "Total network traffic (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rate(substrate_sub_libp2p_network_bytes_total{chain=\"$chain\", node=~\".*validator.*|.*bootnode.*\"}[$__rate_interval])) by (direction)",
     "legendFormat": "Bytes {{direction}} "
    }
   ]
  },
  {
   "title": "Approval checking finality lag (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "polkadot_parachain_approval_checking_finality_lag{chain=\"$chain\", node=~\".*validator.*\"}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "min(substrate_block_height{chain=\"$chain\", node=~\".*validator.*\"}) by (status, node)",
     "legendFormat": "Min {{status}} {{node}}"
    },
    {
     "expr": "max(substrate_block_height{chain=\"$chain\", node=~\".*validator.*\"}) by (status)",
     "legendFormat": "Max {{status}}"
    }
   ]
  },
  {
   "title": "Pending connections errors/second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "avg(rate(substrate_sub_libp2p_pending_connections_errors_total{chain=\"$chain\", node=~\".*validator.*\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Relay chain block time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1/avg(rate(substrate_block_height{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Max {{status}}"
    }
   ]
  },
  {
   "title": "PVF preparation time (heatmap)",
   "type": "heatmap",
   "description": "The time spent in preparing Parachain Validation Function artifacts in seconds.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_pvf_preparation_time_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Authorities and parachain validators",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "sum(polkadot_node_is_active_validator{chain=\"$chain\", node=~\".*validator.*\"})",
     "legendFormat": "Authorities"
    },
    {
     "expr": "sum(polkadot_node_is_parachain_validator{chain=\"$chain\", node=~\".*validator.*\"})",
     "legendFormat": "Parachain validators"
    }
   ]
  },
  {
   "title": "Disputes finality lag (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "polkadot_parachain_disputes_finality_lag{chain=\"$chain\", node=~\".*validator.*\"}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "targets": [
    {
     "expr": "avg(polkadot_parachain_peer_count{chain=\"$chain\", node=~\".*validator.*\"}) by(protocol) ",
     "legendFormat": "avg {{protocol}}"
    },
    {
     "expr": "min(polkadot_parachain_peer_count{chain=\"$chain\", node=~\".*validator.*\"}) by (protocol)",
     "legendFormat": "min {{protocol}}"
    },
    {
     "expr": "max(polkadot_parachain_peer_count{chain=\"$chain\", pod=~\".*validator.*\"}) by (protocol)",
     "legendFormat": "max {{protocol}}"
    }
   ]
  },
  {
   "title": "PVF execution time (heatmap)",
   "type": "heatmap",
   "description": "Parachain Validation Function execution time distribution.  PVFs are expected to have a limited execution time to ensure there is enough time left for the parachain block to be included in the relay block. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_pvf_execution_time_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peer connect/disconnect",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "peers/s" } },
   "targets": [
    {
     "expr": "avg(rate(polkadot_parachain_peer_disconnect_events_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by(protocol) ",
     "legendFormat": "{{protocol}} disconnects"
    },
    {
     "expr": "max(rate(polkadot_parachain_peer_connect_events_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by(protocol) ",
     "legendFormat": "{{protocol}} connects"
    }
   ]
  },
  {
   "title": "Validation code size distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_candidate_validation_code_size_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Validation peerset notification sizes (OUT)",
   "type": "heatmap",
   "description": "Size distribution for messages sent over the validation protocol.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "sum(increase(substrate_sub_libp2p_notifications_sizes_bucket{chain=\"$chain\", protocol=~\".*validation.*\", direction=\"out\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PoV size distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_candidate_validation_pov_size_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block import time (relay chain)",
   "type": "heatmap",
   "description": "Parachain Validation Function execution time distribution.  PVFs are expected to have a limited execution time to ensure there is enough time left for the parachain block to be included in the relay block. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "sum(increase(substrate_block_verification_and_import_time_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PoV size distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(increase(polkadot_parachain_candidate_validation_pov_size_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "PoV size (90th percentile)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(increase(polkadot_parachain_candidate_validation_pov_size_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "PoV size (50th percentile)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(polkadot_parachain_candidate_validation_pov_size_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "PoV size (99th percentile)"
    }
   ]
  },
  {
   "title": "Block inherent create time (relay chain)",
   "type": "heatmap",
   "description": "Parachain Validation Function execution time distribution.  PVFs are expected to have a limited execution time to ensure there is enough time left for the parachain block to be included in the relay block. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "sum(increase(substrate_proposer_create_inherents_time_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time spent pruning av data",
   "type": "heatmap",
   "description": "Parachain Validation Function execution time distribution.  PVFs are expected to have a limited execution time to ensure there is enough time left for the parachain block to be included in the relay block. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_av_store_pruning_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Candidate backing and availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Candidate backing",
   "type": "timeseries",
   "description": "Number of candidates seconded and signed statements.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_candidate_backing_candidates_seconded_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Candidates seconded"
    },
    {
     "expr": "sum(rate(polkadot_parachain_candidate_backing_signed_statements_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Statements signed"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Number of erasure-encoded chunks of data belonging to candidate blocks. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "chunks/s" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_received_availability_chunks_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "AV store chunks received"
    },
    {
     "expr": "sum(rate(polkadot_parachain_availability_recovery_chunk_requests_issued{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Chunks requested"
    }
   ]
  },
  {
   "title": "Provisioner inherent data bitfields",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_provisioner_inherent_data_response_bitfields_sent_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Chunk request duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_availability_recovery_time_chunk_request_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Statement distribution network bridge update ",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "avg(rate(polkadot_parachain_statement_distribution_network_bridge_update_v1_bucket{chain=\"$chain\", node=~\".*validator.*\", message_type=\"circulate_statement\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Provisioner inherent data bitfields",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bitfields" } },
   "targets": [
    {
     "expr": "6*avg(rate(polkadot_parachain_provisioner_inherent_data_response_bitfields_sent_sum{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Bitfields per block"
    },
    {
     "expr": "6*avg(rate(polkadot_parachain_bitfield_distribution_handle_bitfield_distribution_count{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "avg signed bitfields "
    }
   ]
  },
  {
   "title": "Disputes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dispute triggered and outcomes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "disputes/block" } },
     "targets": [
      {
       "expr": "6*avg(rate(polkadot_parachain_candidate_dispute_concluded{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (validity)",
       "legendFormat": "Concluded {{validity}}"
      },
      {
       "expr": "6*avg(rate(polkadot_parachain_candidate_disputes_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
       "legendFormat": "Disputes raised"
      },
      {
       "expr": "6*avg(rate(polkadot_parachain_candidate_dispute_votes{chain=\"$chain\", pod=~\".*validator.*\"}[$__rate_interval])) by (validity)",
       "legendFormat": "{{validity}} votes"
      }
     ]
    },
    {
     "title": "Total initiated disputes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "disputes" } },
     "targets": [
      {
       "expr": "polkadot_parachain_candidate_disputes_total{chain=\"$chain\", node=~\".*validator.*\"}",
       "legendFormat": "Disputes raised"
      }
     ]
    },
    {
     "title": "Dispute statements passed to create_inherent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "disputes/s" } },
     "targets": [
      {
       "expr": "sum(rate(polkadot_parachain_inherent_data_dispute_statements{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (validity)",
       "legendFormat": "Concluded {{validity}}"
      }
     ]
    },
    {
     "title": "Dispute participations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "disputes/s" } },
     "targets": [
      {
       "expr": "max(rate(polkadot_parachain_dispute_participations{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (priority)",
       "legendFormat": "{{priority}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Candidate Validation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Candidate Validation Times (distribution)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 181 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_candidate_validation_validate_from_chain_state_bucket{chain=\"$chain\", node=~\".*validator.*\"} [$__rate_interval])) by (le) +\nsum(increase(polkadot_parachain_candidate_validation_validate_from_exhaustive_bucket{chain=\"$chain\", node=~\".*validator.*\"} [$__rate_interval])) by (le) +\nsum(increase(polkadot_parachain_candidate_validation_validate_candidate_exhaustive_bucket{chain=\"$chain\", node=~\".*validator.*\"} [$__rate_interval])) by (le)\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Candidates imported/seconded per block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "candidate(s)/block" } },
   "targets": [
    {
     "expr": "6*avg(rate(polkadot_parachain_imported_candidates_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Imported"
    },
    {
     "expr": "6*sum(rate(polkadot_parachain_candidate_backing_candidates_seconded_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Seconded"
    }
   ]
  },
  {
   "title": "Candidate validation request (per block)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "6*avg(rate(polkadot_parachain_validation_requests_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (validity)",
     "legendFormat": "{{validity}}"
    }
   ]
  },
  {
   "title": "Approval voting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Assignment Delay Tranches (per block)",
   "type": "heatmap",
   "description": "Approval voting requires that validators which are assigned to check a specific \ncandidate are split up into delay tranches (0.5s each). Then, all validators checks are ordered by the delay \ntranche index. Early tranches of validators will check the candidate first and later tranches act as as backups in case of no shows.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "6*sum(rate(polkadot_parachain_assignments_produced_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Assignments, approvals and no shows observed per validator",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "6*avg(rate(polkadot_parachain_assignments_produced_count{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Assignments"
    },
    {
     "expr": "6*avg(rate(polkadot_parachain_approvals_produced_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (status)",
     "legendFormat": "Approvals ({{status}})"
    },
    {
     "expr": "6*avg(rate(polkadot_parachain_approvals_no_shows_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "No shows"
    }
   ]
  },
  {
   "title": "Assignments produced",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(rate(polkadot_parachain_approvals_imported_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Approvals imported"
    },
    {
     "expr": "avg(rate(polkadot_parachain_assignments_imported_total{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (kind)",
     "legendFormat": "{{kind}} assignments"
    },
    {
     "expr": "max(rate(polkadot_parachain_approvals_no_shows_total{chain=\"$chain\",  node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Max no shows"
    }
   ]
  },
  {
   "title": "Time to recover a PoV",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 209 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_availability_recovery_time_total_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time to recover and check candidate (heatmap)",
   "type": "heatmap",
   "description": "Parachain Validation Function execution time distribution.  PVFs are expected to have a limited execution time to ensure there is enough time left for the parachain block to be included in the relay block. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 219 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_time_recover_and_approve_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Approval vote coalescing",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 219 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_approvals_coalesced_approvals_buckets_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time to Recover and Check Candidate",
   "type": "timeseries",
   "description": "This covers the full time it takes to: recover candidate available data from other validators; check the candidate; issue statement or initiate dispute",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 229 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(polkadot_parachain_time_recover_and_approve_sum{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Erasure recovery (no I/O)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 229 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_availability_recovery_time_erasure_recovery_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Re-encoding chunks timing",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 239 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_availability_reencode_chunks_bucket{chain=\"$chain\", node=~\".*validator.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}