{
 "title": "Substrate - Service Tasks",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(substrate_build_info,chain)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Instance filter",
    "query": {
     "query": "label_values(substrate_build_info{chain=\"$chain\"},node)"
    }
   },
   { "name": "metric_namespace", "label": "Prefix of the metrics", "query": "substrate" }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU time spent on each task",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_tasks_polling_duration_sum{node=~\"${node}\"}[$__rate_interval])) by (task_group)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Task polling rate per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(${metric_namespace}_tasks_polling_duration_count{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Average time it takes to call Future::poll()",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(${metric_namespace}_tasks_polling_duration_sum{node=~\"${node}\"}[$__rate_interval]) / increase(${metric_namespace}_tasks_polling_duration_count{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of tasks started",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(${metric_namespace}_tasks_spawned_total{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of tasks running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${metric_namespace}_tasks_spawned_total{node=~\"${node}\"} - sum(${metric_namespace}_tasks_ended_total{node=~\"${node}\"}) without(reason)\n\n# Fallback if tasks_ended_total is null for that task\nor on(node, task_name) ${metric_namespace}_tasks_spawned_total{node=~\"${node}\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of calls to `Future::poll` that took more than one second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(${metric_namespace}_tasks_polling_duration_bucket{node=~\"${node}\", le=\"+Inf\"}[$__rate_interval])\n    - ignoring(le)\n  irate(${metric_namespace}_tasks_polling_duration_bucket{node=~\"${node}\", le=\"1.024\"}[$__rate_interval]) > 0",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Unbounded Channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unbounded channels size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  ${metric_namespace}_unbounded_channel_len{node=~\"${node}\", action = \"send\"} - ignoring(action) ${metric_namespace}_unbounded_channel_len{node=~\"${node}\", action = \"received\"}\n)\n\n# Fallback if the `received` is null\nor on(node) ${metric_namespace}_unbounded_channel_len{node=~\"${node}\", action = \"send\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Unbounded channels message sending rate (1s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(${metric_namespace}_unbounded_channel_len{node=~\"${node}\", action = \"send\"}[$__rate_interval])",
     "legendFormat": "{{entity}}"
    }
   ]
  }
 ]
}