{
 "title": "Substrate - Networking",
 "description": "Information related to the networking layer of Substrate",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "metric_namespace", "label": "Prefix of the metrics", "query": "substrate" },
   {
    "name": "chain",
    "query": {
     "query": "label_values(substrate_build_info,chain)"
    }
   },
   {
    "name": "node",
    "label": "Instance name filter",
    "query": {
     "query": "label_values(${metric_namespace}_process_start_time_seconds{chain=\"$chain\"},node)"
    }
   },
   {
    "name": "notif_protocol",
    "query": {
     "query": "${metric_namespace}_sub_libp2p_notifications_sizes_count{node=~\"${node}\"}"
    }
   },
   {
    "name": "request_protocol",
    "query": {
     "query": "${metric_namespace}_sub_libp2p_requests_in_success_total_count{node=~\"${node}\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "Transport",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average transport-level (TCP, QUIC, ...) connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"in\", node=~\"${node}\"}) by (node) -\n  sum(${metric_namespace}_sub_libp2p_connections_closed_total{direction=\"in\", node=~\"${node}\"}) by (node)\n)\n\n# Because `closed_total` can be null, this serves as fallback\nor on(node) sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"in\", node=~\"${node}\"}) by (node)",
     "legendFormat": "established (in)"
    },
    {
     "expr": "(\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"out\", node=~\"${node}\"}) by (node) -\n  sum(${metric_namespace}_sub_libp2p_connections_closed_total{direction=\"out\", node=~\"${node}\"}) by (node)\n)\n\n# Because `closed_total` can be null, this serves as fallback\nor on(node) sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"out\", node=~\"${node}\"}) by (node)",
     "legendFormat": "established (out)"
    },
    {
     "expr": "sum by (node) (${metric_namespace}_sub_libp2p_pending_connections{node=~\"${node}\"})",
     "legendFormat": "pending (out)"
    },
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_connections_closed_total{node=~\"${node}\"}[$__interval]))",
     "legendFormat": "closed-per-sec"
    }
   ]
  },
  {
   "title": "Percentage of peers for which we have more than one connection open",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - \n\navg(\n  ${metric_namespace}_sub_libp2p_distinct_peers_connections_opened_total{node=~\"${node}\"} - ${metric_namespace}_sub_libp2p_distinct_peers_connections_closed_total{node=~\"${node}\"}\n) by (node)\n\n/\n\navg(\r\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{node=~\"${node}\"}) by (node) - sum(${metric_namespace}_sub_libp2p_connections_closed_total{node=~\"${node}\"}) by (node)\r\n) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number of incoming connection errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(${metric_namespace}_sub_libp2p_incoming_connections_handshake_errors_total{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "increase(${metric_namespace}_sub_libp2p_listeners_errors_total{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "pre-handshake"
    }
   ]
  },
  {
   "title": "Network bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_network_bytes_total{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Dialing attempt errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(${metric_namespace}_sub_libp2p_pending_connections_errors_total{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Disconnects/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_connections_closed_total{node=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{reason}} ({{direction}})"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of peer slots filled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_peerset_num_requested{node=~\"${node}\"}",
     "legendFormat": "peers-requested"
    },
    {
     "expr": "${metric_namespace}_sub_libp2p_peers_count{node=~\"${node}.*\"}",
     "legendFormat": "peers-count"
    }
   ]
  },
  {
   "title": "Requests (${request_protocol})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "repeat": "request_protocol",
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests emitted per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_requests_out_success_total_count{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval]) + on(node) sum(rate(${metric_namespace}_sub_libp2p_requests_out_failure_total{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (node)\n\nor\n\nrate(${metric_namespace}_sub_libp2p_requests_out_success_total_count{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Outbound requests failures",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 51 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_requests_out_failure_total{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (node, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Median request answer time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 55 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(${metric_namespace}_sub_libp2p_requests_out_success_total_bucket{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (node, le)) > 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "99th percentile request answer time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_requests_out_success_total_bucket{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (node, le)) > 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Requests served per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 63 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_requests_in_success_total_count{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Inbound requests failures",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 67 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_requests_in_failure_total{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (node, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Median request serving time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 71 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(${metric_namespace}_sub_libp2p_requests_in_success_total_bucket{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (node, le))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "99th percentile request serving time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 75 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_requests_in_success_total_bucket{node=~\"${node}\", protocol=\"${request_protocol}\"}[$__rate_interval])) by (node, le))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Notifications (${notif_protocol})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "repeat": "notif_protocol",
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of open substreams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 146 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_notifications_streams_opened_total{node=~\"${node}\", protocol=\"${notif_protocol}\"} - ${metric_namespace}_sub_libp2p_notifications_streams_closed_total{node=~\"${node}\", protocol=\"${notif_protocol}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Substreams closed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 152 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(${metric_namespace}_sub_libp2p_notifications_streams_closed_total{node=~\"${node}\", protocol=\"${notif_protocol}\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number of network notifications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 158 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (direction) (rate(${metric_namespace}_sub_libp2p_notifications_sizes_count{node=~\"${node}\", protocol=\"${notif_protocol}\"}[$__rate_interval]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Average bandwidth used by notifications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 164 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(${metric_namespace}_sub_libp2p_notifications_sizes_sum{node=~\"${node}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Total sizes of notifications waiting to be delivered to the rest of Substrate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 170 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_out_events_notifications_sizes{node=~\"${node}\", protocol=\"${notif_protocol}\", action=\"sent\"} - ignoring(action) ${metric_namespace}_sub_libp2p_out_events_notifications_sizes{node=~\"${node}\", protocol=\"${notif_protocol}\", action=\"received\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average size of sent and received notifications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 176 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_notifications_sizes_sum{node=~\"${node}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction, protocol) / sum(rate(${metric_namespace}_sub_libp2p_notifications_sizes_count{node=~\"${node}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction, protocol)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "99th percentile of size of sent and received notifications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 182 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(${metric_namespace}_sub_libp2p_notifications_sizes_bucket{node=~\"${node}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction, le))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "GrandPa",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 317 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GrandPa messages received from the network, and action",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 318 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(${metric_namespace}_finality_grandpa_communication_gossip_validator_messages{node=~\"${node}\"}[$__interval])",
     "legendFormat": "{{message}} => {{action}}"
    }
   ]
  }
 ]
}